[WIP] Incellbar custom styling
EQWorks/lumen-table pull request #38
Opened 2023-01-20 19:38 UTC by kc-leung

branch off from https://github.com/EQWorks/lumen-table/pull/35

- Added scrollbar if no pagination
- Added formatValue option for each column data
- Added custom barColumnsColor for bar columns ( single color for now can be changed to multiple for different columns based on header key if needed )
- Added default filter search with title - HeaderTitle component

**Figma design file:** 
https://www.figma.com/file/Vr5v8g2MicUtWbcm3q7T3V/Paymi-Retail-Insights-Dashboard?node-id=304%3A105192&t=EBp78fTZPGMamyQQ-0

**Default with bar columns**

![Screen Shot 2023-01-20 at 2 35 26 PM](https://user-images.githubusercontent.com/46459367/213790353-f7bdcb15-d274-4410-af4b-b920e5a66b04.png)

**Custom styling with HeaderTitle component**

![Screen Shot 2023-01-20 at 2 36 11 PM](https://user-images.githubusercontent.com/46459367/213790514-df7edbc0-5114-4918-849d-1bf5398c55b3.png)

2023-01-23 17:24 UTC, geoerika commented
@kc-leung this PR is still WIP.

2023-01-23 17:41 UTC, geoerika requested changes
Maybe we include the d3 functions to calculate colour hues & the extent of data. Let me know what you think.

2023-01-23 17:41 UTC, geoerika commented on src/in-cell-bar.js
> +const adjustBarColor = (amount, color) => {
I believe this is where you can use the d3 linear scale colour function?

2023-01-23 17:41 UTC, geoerika commented on src/index.js
> +            <td className={`table__body-cell border-${defaultStyles.borderType} border-secondary-200 text-secondary-800 ${i === (highlightColumn - 1) && 'font-bold'}`} key={i} {...cell.getCellProps()
Could you please break down this long line on at least 2?

2023-01-23 17:43 UTC, geoerika commented
Ref for d3:
https://www.geeksforgeeks.org/d3-js-d3-extent-function/
https://github.com/EQWorks/react-maps/blob/main/src/components/locus-map/utils/scheme-color.js 
https://www.geeksforgeeks.org/d3-js-d3-extent-function/

2023-01-27 00:15 UTC, geoerika requested changes
Just a note to think about and one too long of a line.

2023-01-27 00:15 UTC, geoerika commented on stories/table-chart.stories.js
> +    classes={{
I see that we will have to add this compact styling in widget studio when implementing the table there. How about we add a prop (ex: compact) and save these compact styling in lumen-table and add them in lumen-table if the prop is true?
This way we help users have a compact table without the hustle of thinking how to create this special styling to pass on to the table.

2023-02-06 13:17 UTC, woozyking commented on src/tableStyle.js
> +const tableStyle = ({ headerTitle, centerHeader, compactTable }) => makeStyles(({
Would recommend naming the module as `src/table-style.js` to stay consistent with the rest of the conventions

2023-02-06 13:17 UTC, woozyking commented on stories/data/dashboard-data.js
> +const data = [
`export default [...]` would do

2023-02-06 15:03 UTC, geoerika approved these changes
Other than Leo's comments, it looks good!

2023-02-06 16:36 UTC, Hamaad102 approved these changes

2023-02-07 14:05 UTC, merged